// Generated by tools/generate-football-competition-catalog.mjs. Do not edit by hand.
export const FOOTBALL_REFERENCE_SEASON = "2026/27";
export const FOOTBALL_REFERENCE_VERIFIED_AT = "2026-08-29";
export const FOOTBALL_REFERENCE_VALID_THROUGH = "2027-06-30T23:59:59Z";

export const FOOTBALL_COMPETITIONS = {
  "premierLeague": {
    "displayName": "Premier League",
    "providerName": "English Premier League",
    "providerAliases": [
      "Premier League"
    ],
    "officialSource": "https://www.premierleague.com/en/news/4365156/new-to-the-premier-league-heres-all-you-need-to-know",
    "expectedClubCount": 20,
    "clubs": [
      {
        "name": "AFC Bournemouth",
        "aliases": [
          "Bournemouth"
        ]
      },
      {
        "name": "Arsenal",
        "aliases": []
      },
      {
        "name": "Aston Villa",
        "aliases": [
          "Villa"
        ]
      },
      {
        "name": "Brentford",
        "aliases": []
      },
      {
        "name": "Brighton & Hove Albion",
        "aliases": [
          "Brighton",
          "Brighton and Hove Albion"
        ]
      },
      {
        "name": "Chelsea",
        "aliases": []
      },
      {
        "name": "Coventry City",
        "aliases": [
          "Coventry"
        ]
      },
      {
        "name": "Crystal Palace",
        "aliases": [
          "Palace"
        ]
      },
      {
        "name": "Everton",
        "aliases": []
      },
      {
        "name": "Fulham",
        "aliases": []
      },
      {
        "name": "Hull City",
        "aliases": [
          "Hull"
        ]
      },
      {
        "name": "Ipswich Town",
        "aliases": [
          "Ipswich"
        ]
      },
      {
        "name": "Leeds United",
        "aliases": [
          "Leeds"
        ]
      },
      {
        "name": "Liverpool",
        "aliases": []
      },
      {
        "name": "Manchester City",
        "aliases": [
          "Man City"
        ]
      },
      {
        "name": "Manchester United",
        "aliases": [
          "Man United",
          "Man Utd"
        ]
      },
      {
        "name": "Newcastle United",
        "aliases": [
          "Newcastle"
        ]
      },
      {
        "name": "Nottingham Forest",
        "aliases": [
          "Nott'm Forest",
          "Nottm Forest",
          "Forest"
        ]
      },
      {
        "name": "Sunderland",
        "aliases": []
      },
      {
        "name": "Tottenham Hotspur",
        "aliases": [
          "Spurs",
          "Tottenham"
        ]
      }
    ]
  },
  "laLiga": {
    "displayName": "La Liga",
    "providerName": "Spanish La Liga",
    "providerAliases": [
      "La Liga"
    ],
    "officialSource": "https://www.laliga.com/es-GB/laliga-easports/clubes",
    "expectedClubCount": 20,
    "clubs": [
      {
        "name": "Athletic Club",
        "aliases": [
          "Athletic Bilbao"
        ]
      },
      {
        "name": "Atlético de Madrid",
        "aliases": [
          "Atletico Madrid"
        ]
      },
      {
        "name": "CA Osasuna",
        "aliases": [
          "Osasuna"
        ]
      },
      {
        "name": "Celta de Vigo",
        "aliases": [
          "Celta",
          "Celta Vigo"
        ]
      },
      {
        "name": "Deportivo Alavés",
        "aliases": [
          "Alaves"
        ]
      },
      {
        "name": "Elche CF",
        "aliases": [
          "Elche"
        ]
      },
      {
        "name": "FC Barcelona",
        "aliases": [
          "Barcelona"
        ]
      },
      {
        "name": "Getafe CF",
        "aliases": [
          "Getafe"
        ]
      },
      {
        "name": "Levante UD",
        "aliases": [
          "Levante"
        ]
      },
      {
        "name": "Málaga CF",
        "aliases": [
          "Malaga"
        ]
      },
      {
        "name": "Racing de Santander",
        "aliases": [
          "Racing Santander"
        ]
      },
      {
        "name": "Rayo Vallecano",
        "aliases": []
      },
      {
        "name": "RC Deportivo",
        "aliases": [
          "Deportivo",
          "Deportivo La Coruna",
          "Deportivo La Coruña",
          "Deportivo de A Coruña"
        ]
      },
      {
        "name": "RCD Espanyol",
        "aliases": [
          "Espanyol"
        ]
      },
      {
        "name": "Real Betis",
        "aliases": [
          "Betis"
        ]
      },
      {
        "name": "Real Madrid",
        "aliases": []
      },
      {
        "name": "Real Sociedad",
        "aliases": []
      },
      {
        "name": "Sevilla FC",
        "aliases": [
          "Sevilla"
        ]
      },
      {
        "name": "Valencia CF",
        "aliases": [
          "Valencia"
        ]
      },
      {
        "name": "Villarreal CF",
        "aliases": [
          "Villarreal"
        ]
      }
    ]
  },
  "serieA": {
    "displayName": "Serie A",
    "providerName": "Italian Serie A",
    "providerAliases": [
      "Serie A"
    ],
    "officialSource": "https://en.legaseriea.it/serie-a/news/looking-forward-to-the-2026-27-serie-a-fixture-list",
    "expectedClubCount": 20,
    "clubs": [
      {
        "name": "AC Milan",
        "aliases": [
          "Milan"
        ]
      },
      {
        "name": "Atalanta",
        "aliases": []
      },
      {
        "name": "Bologna",
        "aliases": []
      },
      {
        "name": "Cagliari",
        "aliases": []
      },
      {
        "name": "Como",
        "aliases": []
      },
      {
        "name": "Fiorentina",
        "aliases": []
      },
      {
        "name": "Frosinone",
        "aliases": []
      },
      {
        "name": "Genoa",
        "aliases": []
      },
      {
        "name": "Inter",
        "aliases": [
          "Inter Milan",
          "Internazionale"
        ]
      },
      {
        "name": "Juventus",
        "aliases": []
      },
      {
        "name": "Lazio",
        "aliases": []
      },
      {
        "name": "Lecce",
        "aliases": []
      },
      {
        "name": "Monza",
        "aliases": []
      },
      {
        "name": "Napoli",
        "aliases": []
      },
      {
        "name": "Parma",
        "aliases": []
      },
      {
        "name": "Roma",
        "aliases": [
          "AS Roma"
        ]
      },
      {
        "name": "Sassuolo",
        "aliases": []
      },
      {
        "name": "Torino",
        "aliases": []
      },
      {
        "name": "Udinese",
        "aliases": []
      },
      {
        "name": "Venezia",
        "aliases": []
      }
    ]
  },
  "bundesliga": {
    "displayName": "Bundesliga",
    "providerName": "German Bundesliga",
    "providerAliases": [
      "Bundesliga"
    ],
    "officialSource": "https://www.bundesliga.com/en/bundesliga/news/2026-27-fixture-lists-now-available-38068",
    "expectedClubCount": 18,
    "clubs": [
      {
        "name": "FC Augsburg",
        "aliases": [
          "Augsburg"
        ]
      },
      {
        "name": "FC Bayern München",
        "aliases": [
          "Bayern",
          "Bayern Munich"
        ]
      },
      {
        "name": "Borussia Dortmund",
        "aliases": [
          "Dortmund"
        ]
      },
      {
        "name": "Borussia Mönchengladbach",
        "aliases": [
          "Monchengladbach",
          "Borussia Monchengladbach",
          "Gladbach"
        ]
      },
      {
        "name": "Eintracht Frankfurt",
        "aliases": [
          "Frankfurt"
        ]
      },
      {
        "name": "SV Elversberg",
        "aliases": [
          "Elversberg"
        ]
      },
      {
        "name": "SC Freiburg",
        "aliases": [
          "Freiburg"
        ]
      },
      {
        "name": "Hamburger SV",
        "aliases": [
          "Hamburg"
        ]
      },
      {
        "name": "TSG Hoffenheim",
        "aliases": [
          "Hoffenheim"
        ]
      },
      {
        "name": "1. FC Köln",
        "aliases": [
          "Koln",
          "Cologne"
        ]
      },
      {
        "name": "Bayer 04 Leverkusen",
        "aliases": [
          "Bayer Leverkusen",
          "Leverkusen"
        ]
      },
      {
        "name": "RB Leipzig",
        "aliases": [
          "Leipzig"
        ]
      },
      {
        "name": "1. FSV Mainz 05",
        "aliases": [
          "Mainz",
          "Mainz 05"
        ]
      },
      {
        "name": "SC Paderborn 07",
        "aliases": [
          "Paderborn"
        ]
      },
      {
        "name": "FC Schalke 04",
        "aliases": [
          "Schalke",
          "Schalke 04"
        ]
      },
      {
        "name": "VfB Stuttgart",
        "aliases": [
          "Stuttgart"
        ]
      },
      {
        "name": "1. FC Union Berlin",
        "aliases": [
          "Union Berlin"
        ]
      },
      {
        "name": "Werder Bremen",
        "aliases": []
      }
    ]
  },
  "ligue1": {
    "displayName": "Ligue 1",
    "providerName": "French Ligue 1",
    "providerAliases": [
      "Ligue 1"
    ],
    "officialSource": "https://ligue1.com/fr/articles/l1_article_5293-les-dates-de-reprise-des-clubs-de-l1-2627",
    "expectedClubCount": 18,
    "clubs": [
      {
        "name": "Angers SCO",
        "aliases": [
          "Angers"
        ]
      },
      {
        "name": "AJ Auxerre",
        "aliases": [
          "Auxerre"
        ]
      },
      {
        "name": "Stade Brestois 29",
        "aliases": [
          "Brest"
        ]
      },
      {
        "name": "Le Havre AC",
        "aliases": [
          "Le Havre"
        ]
      },
      {
        "name": "Le Mans FC",
        "aliases": [
          "Le Mans"
        ]
      },
      {
        "name": "RC Lens",
        "aliases": [
          "Lens"
        ]
      },
      {
        "name": "FC Lorient",
        "aliases": [
          "Lorient"
        ]
      },
      {
        "name": "LOSC Lille",
        "aliases": [
          "Lille"
        ]
      },
      {
        "name": "Olympique Lyonnais",
        "aliases": [
          "Lyon"
        ]
      },
      {
        "name": "Olympique de Marseille",
        "aliases": [
          "Marseille"
        ]
      },
      {
        "name": "AS Monaco",
        "aliases": [
          "Monaco"
        ]
      },
      {
        "name": "OGC Nice",
        "aliases": [
          "Nice"
        ]
      },
      {
        "name": "Paris FC",
        "aliases": []
      },
      {
        "name": "Paris Saint-Germain",
        "aliases": [
          "PSG",
          "Paris Saint Germain"
        ]
      },
      {
        "name": "Stade Rennais FC",
        "aliases": [
          "Rennes"
        ]
      },
      {
        "name": "RC Strasbourg Alsace",
        "aliases": [
          "Strasbourg"
        ]
      },
      {
        "name": "Toulouse FC",
        "aliases": [
          "Toulouse"
        ]
      },
      {
        "name": "ESTAC Troyes",
        "aliases": [
          "Troyes"
        ]
      }
    ]
  },
  "championsLeague": {
    "displayName": "Champions League",
    "providerName": "UEFA Champions League",
    "providerAliases": [
      "Champions League"
    ],
    "officialSource": "https://www.uefa.com/uefachampionsleague/news/02a6-20d57cfcd03e-407c22a7f465-1000--2026-27-champions-league-teams-dates-draws-format-final/",
    "expectedClubCount": 36,
    "clubs": [
      {
        "name": "AEK Athens",
        "aliases": [
          "AEK"
        ]
      },
      {
        "name": "Arsenal",
        "aliases": []
      },
      {
        "name": "Aston Villa",
        "aliases": [
          "Villa"
        ]
      },
      {
        "name": "Atlético de Madrid",
        "aliases": [
          "Atletico Madrid"
        ]
      },
      {
        "name": "Barcelona",
        "aliases": [
          "FC Barcelona"
        ]
      },
      {
        "name": "Bayern München",
        "aliases": [
          "Bayern",
          "Bayern Munich"
        ]
      },
      {
        "name": "Bodø/Glimt",
        "aliases": [
          "Bodo Glimt"
        ]
      },
      {
        "name": "Borussia Dortmund",
        "aliases": [
          "Dortmund"
        ]
      },
      {
        "name": "Club Brugge",
        "aliases": []
      },
      {
        "name": "Como",
        "aliases": []
      },
      {
        "name": "Fenerbahçe",
        "aliases": [
          "Fenerbahce"
        ]
      },
      {
        "name": "Feyenoord",
        "aliases": []
      },
      {
        "name": "Galatasaray",
        "aliases": []
      },
      {
        "name": "Inter",
        "aliases": [
          "Inter Milan"
        ]
      },
      {
        "name": "LASK",
        "aliases": []
      },
      {
        "name": "Lens",
        "aliases": [
          "RC Lens"
        ]
      },
      {
        "name": "Lille",
        "aliases": [
          "LOSC Lille"
        ]
      },
      {
        "name": "Liverpool",
        "aliases": []
      },
      {
        "name": "Manchester City",
        "aliases": [
          "Man City"
        ]
      },
      {
        "name": "Manchester United",
        "aliases": [
          "Man United",
          "Man Utd"
        ]
      },
      {
        "name": "Napoli",
        "aliases": []
      },
      {
        "name": "Paris Saint-Germain",
        "aliases": [
          "Paris",
          "PSG"
        ]
      },
      {
        "name": "Porto",
        "aliases": [
          "FC Porto"
        ]
      },
      {
        "name": "PSV",
        "aliases": [
          "PSV Eindhoven"
        ]
      },
      {
        "name": "RB Leipzig",
        "aliases": [
          "Leipzig"
        ]
      },
      {
        "name": "Real Betis",
        "aliases": [
          "Betis"
        ]
      },
      {
        "name": "Real Madrid",
        "aliases": []
      },
      {
        "name": "Roma",
        "aliases": [
          "AS Roma"
        ]
      },
      {
        "name": "Sabah",
        "aliases": []
      },
      {
        "name": "Shakhtar Donetsk",
        "aliases": [
          "Shakhtar"
        ]
      },
      {
        "name": "Slavia Praha",
        "aliases": [
          "Slavia Prague"
        ]
      },
      {
        "name": "Slovan Bratislava",
        "aliases": []
      },
      {
        "name": "Sporting CP",
        "aliases": [
          "Sporting Lisbon"
        ]
      },
      {
        "name": "Stuttgart",
        "aliases": [
          "VfB Stuttgart"
        ]
      },
      {
        "name": "Viking",
        "aliases": []
      },
      {
        "name": "Villarreal",
        "aliases": [
          "Villarreal CF"
        ]
      }
    ]
  },
  "europaLeague": {
    "displayName": "UEFA Europa League",
    "providerName": "UEFA Europa League",
    "providerAliases": [
      "Europa League"
    ],
    "officialSource": "https://www.uefa.com/uefaeuropaleague/news/02a8-216e9cafba52-f039617d7982-1000--2026-27-europa-league-league-phase-draw-contenders-learn/",
    "expectedClubCount": 36,
    "clubs": [
      {
        "name": "Anderlecht",
        "aliases": []
      },
      {
        "name": "Ararat-Armenia",
        "aliases": []
      },
      {
        "name": "AZ Alkmaar",
        "aliases": [
          "AZ"
        ]
      },
      {
        "name": "Benfica",
        "aliases": []
      },
      {
        "name": "Beşiktaş",
        "aliases": [
          "Besiktas"
        ]
      },
      {
        "name": "Bournemouth",
        "aliases": [
          "AFC Bournemouth"
        ]
      },
      {
        "name": "Celje",
        "aliases": []
      },
      {
        "name": "Celta",
        "aliases": [
          "Celta Vigo"
        ]
      },
      {
        "name": "Celtic",
        "aliases": []
      },
      {
        "name": "Crystal Palace",
        "aliases": [
          "Palace"
        ]
      },
      {
        "name": "Ferencváros",
        "aliases": [
          "Ferencvaros"
        ]
      },
      {
        "name": "GNK Dinamo",
        "aliases": [
          "Dinamo Zagreb"
        ]
      },
      {
        "name": "Hapoel Be'er Sheva",
        "aliases": [
          "H. Beer-Sheva",
          "Hapoel Beer Sheva"
        ]
      },
      {
        "name": "Hoffenheim",
        "aliases": [
          "TSG Hoffenheim"
        ]
      },
      {
        "name": "Jagiellonia",
        "aliases": []
      },
      {
        "name": "Juventus",
        "aliases": []
      },
      {
        "name": "Lech Poznań",
        "aliases": [
          "Lech Poznan"
        ]
      },
      {
        "name": "Bayer Leverkusen",
        "aliases": [
          "Leverkusen"
        ]
      },
      {
        "name": "Levski Sofia",
        "aliases": []
      },
      {
        "name": "Lillestrøm",
        "aliases": [
          "Lillestrom"
        ]
      },
      {
        "name": "Lyon",
        "aliases": [
          "Olympique Lyonnais"
        ]
      },
      {
        "name": "Marseille",
        "aliases": [
          "Olympique Marseille"
        ]
      },
      {
        "name": "AC Milan",
        "aliases": [
          "Milan"
        ]
      },
      {
        "name": "N.E.C.",
        "aliases": [
          "NEC Nijmegen"
        ]
      },
      {
        "name": "OFI Crete",
        "aliases": [
          "OFI"
        ]
      },
      {
        "name": "Olympiacos",
        "aliases": []
      },
      {
        "name": "Omonia",
        "aliases": []
      },
      {
        "name": "Real Sociedad",
        "aliases": []
      },
      {
        "name": "Rennes",
        "aliases": [
          "Stade Rennais"
        ]
      },
      {
        "name": "Salzburg",
        "aliases": [
          "Red Bull Salzburg"
        ]
      },
      {
        "name": "Sparta Praha",
        "aliases": [
          "Sparta Prague"
        ]
      },
      {
        "name": "Sturm Graz",
        "aliases": []
      },
      {
        "name": "Sunderland",
        "aliases": []
      },
      {
        "name": "Torreense",
        "aliases": []
      },
      {
        "name": "Union SG",
        "aliases": [
          "Union Saint-Gilloise"
        ]
      },
      {
        "name": "Viktoria Plzeň",
        "aliases": [
          "Viktoria Plzen"
        ]
      }
    ]
  }
} as const;

export const ADDITIONAL_FOOTBALL_CLUB_IDENTITIES = [
  {
    "name": "West Ham United",
    "aliases": [
      "West Ham"
    ]
  },
  {
    "name": "Wolverhampton Wanderers",
    "aliases": [
      "Wolves"
    ]
  }
] as const;

export type CurrentFootballCompetitionId = keyof typeof FOOTBALL_COMPETITIONS;

function normalizedKey(value: string) {
  const ignored = new Set(["fc", "afc", "cf", "ac", "club", "sc", "sv", "rc", "rcd", "ud", "losc", "ogc", "estac", "stade", "olympique", "and"]);
  return value.normalize("NFD").replace(/\p{Diacritic}/gu, "").toLowerCase().split(/[^a-z0-9]+/).filter((token) => token && !ignored.has(token)).map((token) => token === "utd" ? "united" : token).join("");
}

function isNonSeniorTeam(value: string) {
  return /\b(?:u(?:18|19|21|23)|under[ -]?(?:18|19|21|23)|women|ladies|youth|academy|reserves?)\b/i.test(value);
}

export function currentCompetitionOfficialNames(id: CurrentFootballCompetitionId) {
  return FOOTBALL_COMPETITIONS[id].clubs.map((club) => club.name);
}

export function isCurrentCompetitionClub(id: CurrentFootballCompetitionId, value: string) {
  if (isNonSeniorTeam(value)) return false;
  const key = normalizedKey(value);
  return FOOTBALL_COMPETITIONS[id].clubs.some((club) => [club.name, ...club.aliases].some((name) => normalizedKey(name) === key));
}

export function isCurrentCompetitionPair(id: CurrentFootballCompetitionId, home: string, away: string) {
  return isCurrentCompetitionClub(id, home) && isCurrentCompetitionClub(id, away);
}

export function canonicalFootballClubId(value: string) {
  if (isNonSeniorTeam(value)) return undefined;
  const key = normalizedKey(value);
  const matches = new Set<string>();
  const considerClub = (club: { readonly name: string; readonly aliases: readonly string[] }) => {
      if ([club.name, ...club.aliases].some((name) => normalizedKey(name) === key)) {
        matches.add(normalizedKey(club.name));
      }
  };
  for (const competition of Object.values(FOOTBALL_COMPETITIONS)) {
    for (const club of competition.clubs) considerClub(club);
  }
  for (const club of ADDITIONAL_FOOTBALL_CLUB_IDENTITIES) considerClub(club);
  return matches.size === 1 ? matches.values().next().value : undefined;
}

export function canonicalFootballTeamKey(value: string) {
  return canonicalFootballClubId(value) ?? normalizedKey(value);
}

export function isFootballReferenceFresh(at = new Date()) {
  return at.getTime() <= Date.parse(FOOTBALL_REFERENCE_VALID_THROUGH);
}
