// Generated by tools/generate-football-competition-catalog.mjs. Do not edit by hand.
import Foundation

enum FootballCompetitionID: String, CaseIterable, Codable, Sendable {
    case premierLeague
    case laLiga
    case serieA
    case bundesliga
    case ligue1
    case championsLeague
    case europaLeague
}

struct FootballCompetitionClub: Equatable, Sendable {
    let name: String
    let aliases: [String]
}

struct FootballCompetitionSnapshot: Equatable, Sendable {
    let id: FootballCompetitionID
    let displayName: String
    let providerName: String
    let providerAliases: [String]
    let officialSource: URL
    let expectedClubCount: Int
    let clubs: [FootballCompetitionClub]

    var officialClubNames: [String] { clubs.map(\.name) }
    var searchAliases: [String] { clubs.flatMap { [$0.name] + $0.aliases } }
}

enum FootballCompetitionCatalog {
    static let schemaVersion = 1
    static let seasonLabel = "2026/27"
    static let verifiedAt = ISO8601DateFormatter().date(from: "2026-08-29T00:00:00Z")!
    static let validThrough = ISO8601DateFormatter().date(from: "2027-06-30T23:59:59Z")!

    static let additionalClubIdentities: [FootballCompetitionClub] = [
        FootballCompetitionClub(name: "West Ham United", aliases: ["West Ham"]),
        FootballCompetitionClub(name: "Wolverhampton Wanderers", aliases: ["Wolves"])
    ]

    static let snapshots: [FootballCompetitionID: FootballCompetitionSnapshot] = [
        .premierLeague: FootballCompetitionSnapshot(
            id: .premierLeague,
            displayName: "Premier League",
            providerName: "English Premier League",
            providerAliases: ["Premier League"],
            officialSource: URL(string: "https://www.premierleague.com/en/news/4365156/new-to-the-premier-league-heres-all-you-need-to-know")!,
            expectedClubCount: 20,
            clubs: [
                FootballCompetitionClub(name: "AFC Bournemouth", aliases: ["Bournemouth"]),
                FootballCompetitionClub(name: "Arsenal", aliases: []),
                FootballCompetitionClub(name: "Aston Villa", aliases: ["Villa"]),
                FootballCompetitionClub(name: "Brentford", aliases: []),
                FootballCompetitionClub(name: "Brighton & Hove Albion", aliases: ["Brighton", "Brighton and Hove Albion"]),
                FootballCompetitionClub(name: "Chelsea", aliases: []),
                FootballCompetitionClub(name: "Coventry City", aliases: ["Coventry"]),
                FootballCompetitionClub(name: "Crystal Palace", aliases: ["Palace"]),
                FootballCompetitionClub(name: "Everton", aliases: []),
                FootballCompetitionClub(name: "Fulham", aliases: []),
                FootballCompetitionClub(name: "Hull City", aliases: ["Hull"]),
                FootballCompetitionClub(name: "Ipswich Town", aliases: ["Ipswich"]),
                FootballCompetitionClub(name: "Leeds United", aliases: ["Leeds"]),
                FootballCompetitionClub(name: "Liverpool", aliases: []),
                FootballCompetitionClub(name: "Manchester City", aliases: ["Man City"]),
                FootballCompetitionClub(name: "Manchester United", aliases: ["Man United", "Man Utd"]),
                FootballCompetitionClub(name: "Newcastle United", aliases: ["Newcastle"]),
                FootballCompetitionClub(name: "Nottingham Forest", aliases: ["Nott'm Forest", "Nottm Forest", "Forest"]),
                FootballCompetitionClub(name: "Sunderland", aliases: []),
                FootballCompetitionClub(name: "Tottenham Hotspur", aliases: ["Spurs", "Tottenham"])
            ]
        ),
        .laLiga: FootballCompetitionSnapshot(
            id: .laLiga,
            displayName: "La Liga",
            providerName: "Spanish La Liga",
            providerAliases: ["La Liga"],
            officialSource: URL(string: "https://www.laliga.com/es-GB/laliga-easports/clubes")!,
            expectedClubCount: 20,
            clubs: [
                FootballCompetitionClub(name: "Athletic Club", aliases: ["Athletic Bilbao"]),
                FootballCompetitionClub(name: "Atlético de Madrid", aliases: ["Atletico Madrid"]),
                FootballCompetitionClub(name: "CA Osasuna", aliases: ["Osasuna"]),
                FootballCompetitionClub(name: "Celta de Vigo", aliases: ["Celta", "Celta Vigo"]),
                FootballCompetitionClub(name: "Deportivo Alavés", aliases: ["Alaves"]),
                FootballCompetitionClub(name: "Elche CF", aliases: ["Elche"]),
                FootballCompetitionClub(name: "FC Barcelona", aliases: ["Barcelona"]),
                FootballCompetitionClub(name: "Getafe CF", aliases: ["Getafe"]),
                FootballCompetitionClub(name: "Levante UD", aliases: ["Levante"]),
                FootballCompetitionClub(name: "Málaga CF", aliases: ["Malaga"]),
                FootballCompetitionClub(name: "Racing de Santander", aliases: ["Racing Santander"]),
                FootballCompetitionClub(name: "Rayo Vallecano", aliases: []),
                FootballCompetitionClub(name: "RC Deportivo", aliases: ["Deportivo", "Deportivo La Coruna", "Deportivo La Coruña", "Deportivo de A Coruña"]),
                FootballCompetitionClub(name: "RCD Espanyol", aliases: ["Espanyol"]),
                FootballCompetitionClub(name: "Real Betis", aliases: ["Betis"]),
                FootballCompetitionClub(name: "Real Madrid", aliases: []),
                FootballCompetitionClub(name: "Real Sociedad", aliases: []),
                FootballCompetitionClub(name: "Sevilla FC", aliases: ["Sevilla"]),
                FootballCompetitionClub(name: "Valencia CF", aliases: ["Valencia"]),
                FootballCompetitionClub(name: "Villarreal CF", aliases: ["Villarreal"])
            ]
        ),
        .serieA: FootballCompetitionSnapshot(
            id: .serieA,
            displayName: "Serie A",
            providerName: "Italian Serie A",
            providerAliases: ["Serie A"],
            officialSource: URL(string: "https://en.legaseriea.it/serie-a/news/looking-forward-to-the-2026-27-serie-a-fixture-list")!,
            expectedClubCount: 20,
            clubs: [
                FootballCompetitionClub(name: "AC Milan", aliases: ["Milan"]),
                FootballCompetitionClub(name: "Atalanta", aliases: []),
                FootballCompetitionClub(name: "Bologna", aliases: []),
                FootballCompetitionClub(name: "Cagliari", aliases: []),
                FootballCompetitionClub(name: "Como", aliases: []),
                FootballCompetitionClub(name: "Fiorentina", aliases: []),
                FootballCompetitionClub(name: "Frosinone", aliases: []),
                FootballCompetitionClub(name: "Genoa", aliases: []),
                FootballCompetitionClub(name: "Inter", aliases: ["Inter Milan", "Internazionale"]),
                FootballCompetitionClub(name: "Juventus", aliases: []),
                FootballCompetitionClub(name: "Lazio", aliases: []),
                FootballCompetitionClub(name: "Lecce", aliases: []),
                FootballCompetitionClub(name: "Monza", aliases: []),
                FootballCompetitionClub(name: "Napoli", aliases: []),
                FootballCompetitionClub(name: "Parma", aliases: []),
                FootballCompetitionClub(name: "Roma", aliases: ["AS Roma"]),
                FootballCompetitionClub(name: "Sassuolo", aliases: []),
                FootballCompetitionClub(name: "Torino", aliases: []),
                FootballCompetitionClub(name: "Udinese", aliases: []),
                FootballCompetitionClub(name: "Venezia", aliases: [])
            ]
        ),
        .bundesliga: FootballCompetitionSnapshot(
            id: .bundesliga,
            displayName: "Bundesliga",
            providerName: "German Bundesliga",
            providerAliases: ["Bundesliga"],
            officialSource: URL(string: "https://www.bundesliga.com/en/bundesliga/news/2026-27-fixture-lists-now-available-38068")!,
            expectedClubCount: 18,
            clubs: [
                FootballCompetitionClub(name: "FC Augsburg", aliases: ["Augsburg"]),
                FootballCompetitionClub(name: "FC Bayern München", aliases: ["Bayern", "Bayern Munich"]),
                FootballCompetitionClub(name: "Borussia Dortmund", aliases: ["Dortmund"]),
                FootballCompetitionClub(name: "Borussia Mönchengladbach", aliases: ["Monchengladbach", "Borussia Monchengladbach", "Gladbach"]),
                FootballCompetitionClub(name: "Eintracht Frankfurt", aliases: ["Frankfurt"]),
                FootballCompetitionClub(name: "SV Elversberg", aliases: ["Elversberg"]),
                FootballCompetitionClub(name: "SC Freiburg", aliases: ["Freiburg"]),
                FootballCompetitionClub(name: "Hamburger SV", aliases: ["Hamburg"]),
                FootballCompetitionClub(name: "TSG Hoffenheim", aliases: ["Hoffenheim"]),
                FootballCompetitionClub(name: "1. FC Köln", aliases: ["Koln", "Cologne"]),
                FootballCompetitionClub(name: "Bayer 04 Leverkusen", aliases: ["Bayer Leverkusen", "Leverkusen"]),
                FootballCompetitionClub(name: "RB Leipzig", aliases: ["Leipzig"]),
                FootballCompetitionClub(name: "1. FSV Mainz 05", aliases: ["Mainz", "Mainz 05"]),
                FootballCompetitionClub(name: "SC Paderborn 07", aliases: ["Paderborn"]),
                FootballCompetitionClub(name: "FC Schalke 04", aliases: ["Schalke", "Schalke 04"]),
                FootballCompetitionClub(name: "VfB Stuttgart", aliases: ["Stuttgart"]),
                FootballCompetitionClub(name: "1. FC Union Berlin", aliases: ["Union Berlin"]),
                FootballCompetitionClub(name: "Werder Bremen", aliases: [])
            ]
        ),
        .ligue1: FootballCompetitionSnapshot(
            id: .ligue1,
            displayName: "Ligue 1",
            providerName: "French Ligue 1",
            providerAliases: ["Ligue 1"],
            officialSource: URL(string: "https://ligue1.com/fr/articles/l1_article_5293-les-dates-de-reprise-des-clubs-de-l1-2627")!,
            expectedClubCount: 18,
            clubs: [
                FootballCompetitionClub(name: "Angers SCO", aliases: ["Angers"]),
                FootballCompetitionClub(name: "AJ Auxerre", aliases: ["Auxerre"]),
                FootballCompetitionClub(name: "Stade Brestois 29", aliases: ["Brest"]),
                FootballCompetitionClub(name: "Le Havre AC", aliases: ["Le Havre"]),
                FootballCompetitionClub(name: "Le Mans FC", aliases: ["Le Mans"]),
                FootballCompetitionClub(name: "RC Lens", aliases: ["Lens"]),
                FootballCompetitionClub(name: "FC Lorient", aliases: ["Lorient"]),
                FootballCompetitionClub(name: "LOSC Lille", aliases: ["Lille"]),
                FootballCompetitionClub(name: "Olympique Lyonnais", aliases: ["Lyon"]),
                FootballCompetitionClub(name: "Olympique de Marseille", aliases: ["Marseille"]),
                FootballCompetitionClub(name: "AS Monaco", aliases: ["Monaco"]),
                FootballCompetitionClub(name: "OGC Nice", aliases: ["Nice"]),
                FootballCompetitionClub(name: "Paris FC", aliases: []),
                FootballCompetitionClub(name: "Paris Saint-Germain", aliases: ["PSG", "Paris Saint Germain"]),
                FootballCompetitionClub(name: "Stade Rennais FC", aliases: ["Rennes"]),
                FootballCompetitionClub(name: "RC Strasbourg Alsace", aliases: ["Strasbourg"]),
                FootballCompetitionClub(name: "Toulouse FC", aliases: ["Toulouse"]),
                FootballCompetitionClub(name: "ESTAC Troyes", aliases: ["Troyes"])
            ]
        ),
        .championsLeague: FootballCompetitionSnapshot(
            id: .championsLeague,
            displayName: "Champions League",
            providerName: "UEFA Champions League",
            providerAliases: ["Champions League"],
            officialSource: URL(string: "https://www.uefa.com/uefachampionsleague/news/02a6-20d57cfcd03e-407c22a7f465-1000--2026-27-champions-league-teams-dates-draws-format-final/")!,
            expectedClubCount: 36,
            clubs: [
                FootballCompetitionClub(name: "AEK Athens", aliases: ["AEK"]),
                FootballCompetitionClub(name: "Arsenal", aliases: []),
                FootballCompetitionClub(name: "Aston Villa", aliases: ["Villa"]),
                FootballCompetitionClub(name: "Atlético de Madrid", aliases: ["Atletico Madrid"]),
                FootballCompetitionClub(name: "Barcelona", aliases: ["FC Barcelona"]),
                FootballCompetitionClub(name: "Bayern München", aliases: ["Bayern", "Bayern Munich"]),
                FootballCompetitionClub(name: "Bodø/Glimt", aliases: ["Bodo Glimt"]),
                FootballCompetitionClub(name: "Borussia Dortmund", aliases: ["Dortmund"]),
                FootballCompetitionClub(name: "Club Brugge", aliases: []),
                FootballCompetitionClub(name: "Como", aliases: []),
                FootballCompetitionClub(name: "Fenerbahçe", aliases: ["Fenerbahce"]),
                FootballCompetitionClub(name: "Feyenoord", aliases: []),
                FootballCompetitionClub(name: "Galatasaray", aliases: []),
                FootballCompetitionClub(name: "Inter", aliases: ["Inter Milan"]),
                FootballCompetitionClub(name: "LASK", aliases: []),
                FootballCompetitionClub(name: "Lens", aliases: ["RC Lens"]),
                FootballCompetitionClub(name: "Lille", aliases: ["LOSC Lille"]),
                FootballCompetitionClub(name: "Liverpool", aliases: []),
                FootballCompetitionClub(name: "Manchester City", aliases: ["Man City"]),
                FootballCompetitionClub(name: "Manchester United", aliases: ["Man United", "Man Utd"]),
                FootballCompetitionClub(name: "Napoli", aliases: []),
                FootballCompetitionClub(name: "Paris Saint-Germain", aliases: ["Paris", "PSG"]),
                FootballCompetitionClub(name: "Porto", aliases: ["FC Porto"]),
                FootballCompetitionClub(name: "PSV", aliases: ["PSV Eindhoven"]),
                FootballCompetitionClub(name: "RB Leipzig", aliases: ["Leipzig"]),
                FootballCompetitionClub(name: "Real Betis", aliases: ["Betis"]),
                FootballCompetitionClub(name: "Real Madrid", aliases: []),
                FootballCompetitionClub(name: "Roma", aliases: ["AS Roma"]),
                FootballCompetitionClub(name: "Sabah", aliases: []),
                FootballCompetitionClub(name: "Shakhtar Donetsk", aliases: ["Shakhtar"]),
                FootballCompetitionClub(name: "Slavia Praha", aliases: ["Slavia Prague"]),
                FootballCompetitionClub(name: "Slovan Bratislava", aliases: []),
                FootballCompetitionClub(name: "Sporting CP", aliases: ["Sporting Lisbon"]),
                FootballCompetitionClub(name: "Stuttgart", aliases: ["VfB Stuttgart"]),
                FootballCompetitionClub(name: "Viking", aliases: []),
                FootballCompetitionClub(name: "Villarreal", aliases: ["Villarreal CF"])
            ]
        ),
        .europaLeague: FootballCompetitionSnapshot(
            id: .europaLeague,
            displayName: "UEFA Europa League",
            providerName: "UEFA Europa League",
            providerAliases: ["Europa League"],
            officialSource: URL(string: "https://www.uefa.com/uefaeuropaleague/news/02a8-216e9cafba52-f039617d7982-1000--2026-27-europa-league-league-phase-draw-contenders-learn/")!,
            expectedClubCount: 36,
            clubs: [
                FootballCompetitionClub(name: "Anderlecht", aliases: []),
                FootballCompetitionClub(name: "Ararat-Armenia", aliases: []),
                FootballCompetitionClub(name: "AZ Alkmaar", aliases: ["AZ"]),
                FootballCompetitionClub(name: "Benfica", aliases: []),
                FootballCompetitionClub(name: "Beşiktaş", aliases: ["Besiktas"]),
                FootballCompetitionClub(name: "Bournemouth", aliases: ["AFC Bournemouth"]),
                FootballCompetitionClub(name: "Celje", aliases: []),
                FootballCompetitionClub(name: "Celta", aliases: ["Celta Vigo"]),
                FootballCompetitionClub(name: "Celtic", aliases: []),
                FootballCompetitionClub(name: "Crystal Palace", aliases: ["Palace"]),
                FootballCompetitionClub(name: "Ferencváros", aliases: ["Ferencvaros"]),
                FootballCompetitionClub(name: "GNK Dinamo", aliases: ["Dinamo Zagreb"]),
                FootballCompetitionClub(name: "Hapoel Be'er Sheva", aliases: ["H. Beer-Sheva", "Hapoel Beer Sheva"]),
                FootballCompetitionClub(name: "Hoffenheim", aliases: ["TSG Hoffenheim"]),
                FootballCompetitionClub(name: "Jagiellonia", aliases: []),
                FootballCompetitionClub(name: "Juventus", aliases: []),
                FootballCompetitionClub(name: "Lech Poznań", aliases: ["Lech Poznan"]),
                FootballCompetitionClub(name: "Bayer Leverkusen", aliases: ["Leverkusen"]),
                FootballCompetitionClub(name: "Levski Sofia", aliases: []),
                FootballCompetitionClub(name: "Lillestrøm", aliases: ["Lillestrom"]),
                FootballCompetitionClub(name: "Lyon", aliases: ["Olympique Lyonnais"]),
                FootballCompetitionClub(name: "Marseille", aliases: ["Olympique Marseille"]),
                FootballCompetitionClub(name: "AC Milan", aliases: ["Milan"]),
                FootballCompetitionClub(name: "N.E.C.", aliases: ["NEC Nijmegen"]),
                FootballCompetitionClub(name: "OFI Crete", aliases: ["OFI"]),
                FootballCompetitionClub(name: "Olympiacos", aliases: []),
                FootballCompetitionClub(name: "Omonia", aliases: []),
                FootballCompetitionClub(name: "Real Sociedad", aliases: []),
                FootballCompetitionClub(name: "Rennes", aliases: ["Stade Rennais"]),
                FootballCompetitionClub(name: "Salzburg", aliases: ["Red Bull Salzburg"]),
                FootballCompetitionClub(name: "Sparta Praha", aliases: ["Sparta Prague"]),
                FootballCompetitionClub(name: "Sturm Graz", aliases: []),
                FootballCompetitionClub(name: "Sunderland", aliases: []),
                FootballCompetitionClub(name: "Torreense", aliases: []),
                FootballCompetitionClub(name: "Union SG", aliases: ["Union Saint-Gilloise"]),
                FootballCompetitionClub(name: "Viktoria Plzeň", aliases: ["Viktoria Plzen"])
            ]
        )
    ]

    static func snapshot(_ id: FootballCompetitionID) -> FootballCompetitionSnapshot {
        snapshots[id]!
    }

    static func officialClubNames(for id: FootballCompetitionID) -> [String] {
        snapshot(id).officialClubNames
    }

    static func searchAliases(for id: FootballCompetitionID) -> [String] {
        snapshot(id).searchAliases
    }

    static func isFresh(at date: Date = Date()) -> Bool {
        date <= validThrough
    }

    static func contains(_ rawName: String, in id: FootballCompetitionID) -> Bool {
        officialName(for: rawName, in: id) != nil
    }

    static func containsBoth(home: String, away: String, in id: FootballCompetitionID) -> Bool {
        contains(home, in: id) && contains(away, in: id)
    }

    /// One provider-independent senior-club identity shared by matching, filtering and fixtures.
    static func canonicalClubID(for rawName: String) -> String? {
        guard !isNonSeniorTeam(rawName) else { return nil }
        let key = normalizedKey(rawName)
        let allClubs = snapshots.values.flatMap(\.clubs) + additionalClubIdentities
        let matches = Set(allClubs.compactMap { club in
                ([club.name] + club.aliases).contains { normalizedKey($0) == key }
                    ? normalizedKey(club.name)
                    : nil
        })
        return matches.count == 1 ? matches.first : nil
    }

    /// Known clubs collapse to their canonical identity; unknown teams retain a deterministic key.
    static func canonicalTeamKey(_ rawName: String) -> String {
        canonicalClubID(for: rawName) ?? normalizedKey(rawName)
    }

    static func officialName(for rawName: String, in id: FootballCompetitionID) -> String? {
        guard !isNonSeniorTeam(rawName) else { return nil }
        let key = normalizedKey(rawName)
        return snapshot(id).clubs.first { club in
            ([club.name] + club.aliases).contains { normalizedKey($0) == key }
        }?.name
    }

    static func providerBootstrap() -> [String: [String]] {
        Dictionary(uniqueKeysWithValues: snapshots.values.flatMap { snapshot in
            ([snapshot.providerName] + snapshot.providerAliases).map { ($0, snapshot.officialClubNames) }
        })
    }

    static func socialFallback() -> [String: [String]] {
        Dictionary(uniqueKeysWithValues: snapshots.values.map { ($0.displayName, $0.officialClubNames) })
    }

    private static func isNonSeniorTeam(_ value: String) -> Bool {
        let pattern = #"\b(?:u(?:18|19|21|23)|under[ -]?(?:18|19|21|23)|women|ladies|youth|academy|reserves?)\b"#
        return value.lowercased().range(of: pattern, options: .regularExpression) != nil
    }

    private static func normalizedKey(_ value: String) -> String {
        let folded = value.folding(options: [.diacriticInsensitive, .caseInsensitive], locale: Locale(identifier: "en_US_POSIX"))
        let ignored: Set<String> = ["fc", "afc", "cf", "ac", "club", "sc", "sv", "rc", "rcd", "ud", "losc", "ogc", "estac", "stade", "olympique", "and"]
        return folded.components(separatedBy: CharacterSet.alphanumerics.inverted)
            .filter { !$0.isEmpty && !ignored.contains($0.lowercased()) }
            .map { $0.lowercased() == "utd" ? "united" : $0.lowercased() }
            .joined()
    }
}

enum PremierLeagueClubCatalog {
    static let seasonLabel = FootballCompetitionCatalog.seasonLabel
    static let officialClubNames = FootballCompetitionCatalog.officialClubNames(for: .premierLeague)
    static let searchAliases = FootballCompetitionCatalog.searchAliases(for: .premierLeague)
    static func contains(_ rawName: String) -> Bool { FootballCompetitionCatalog.contains(rawName, in: .premierLeague) }
    static func officialName(for rawName: String) -> String? { FootballCompetitionCatalog.officialName(for: rawName, in: .premierLeague) }
    static func containsBoth(home: String, away: String) -> Bool { FootballCompetitionCatalog.containsBoth(home: home, away: away, in: .premierLeague) }
}
