#!/usr/bin/env bash
# Run a production-style Fotty Web build on localhost only — does not touch homelab/live deploy.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WEB_DIR="$ROOT_DIR/web"
PORT="${FOTTY_LOCAL_PREVIEW_PORT:-3020}"
HOST="${FOTTY_LOCAL_PREVIEW_HOST:-127.0.0.1}"
PID_FILE="${TMPDIR:-/tmp}/fotty-web-preview-${PORT}.pid"
LOG_FILE="${TMPDIR:-/tmp}/fotty-web-preview-${PORT}.log"

usage() {
  cat <<EOF
Usage: $(basename "$0") [--stop | --no-build | --foreground | --status]

  Builds (unless --no-build) and starts the standalone Next server on:
    http://${HOST}:${PORT}

  Env is loaded from web/.env.local when present. Production rules apply:
  - NEXT_PUBLIC_FOTTY_ALLOW_LOCAL_AUTH is stripped for the build/runtime
  - FOTTY_WATCH_STREAM_SECRET defaults to a local-only value if unset

  Homelab APIs (P2P/scraper/PocketBase) are still used when configured in .env.local.
  Only the local web container is started — live fotty.pixel-invoice.com is untouched.

Options:
  --stop        Stop the preview server on port ${PORT}
  --no-build    Skip npm run build:standalone and restart the last build
  --foreground  Run in the foreground (best for Safari testing — keep the tab open)
  --status      Print whether the preview is listening on port ${PORT}
EOF
}

preview_status() {
  if lsof -iTCP:"${PORT}" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "running http://${HOST}:${PORT}"
    return 0
  fi
  echo "stopped (nothing listening on ${PORT})"
  return 1
}

start_server() {
  PREVIEW_ENV="${TMPDIR:-/tmp}/fotty-preview-${PORT}.env"
  cat >"$PREVIEW_ENV" <<EOF
NODE_ENV=production
PORT=${PORT}
HOSTNAME=${HOST}
NEXT_PUBLIC_SITE_URL=http://${HOST}:${PORT}
FOTTY_WATCH_STREAM_SECRET=${FOTTY_WATCH_STREAM_SECRET}
NEXT_PUBLIC_FOTTY_ALLOW_LOCAL_AUTH=
EOF

  local node_cmd=(node)
  if [[ -f "$WEB_DIR/.env.local" ]]; then
    node_cmd+=(--env-file="$WEB_DIR/.env.local" --env-file="$PREVIEW_ENV")
  else
    node_cmd+=(--env-file="$PREVIEW_ENV")
  fi
  node_cmd+=("$WEB_DIR/.next/standalone/server.js")

  if [[ "${FOREGROUND:-0}" -eq 1 ]]; then
    echo "Foreground preview on http://${HOST}:${PORT} (Ctrl+C to stop)"
    cd "$WEB_DIR"
    exec "${node_cmd[@]}"
  fi

  echo "Starting local production preview on http://${HOST}:${PORT} …"
  cd "$WEB_DIR"
  : >"$LOG_FILE"
  nohup "${node_cmd[@]}" >>"$LOG_FILE" 2>&1 &
  local pid=$!
  disown -h "$pid" 2>/dev/null || true
  echo "$pid" >"$PID_FILE"
}

load_env_local() {
  local env_file="$WEB_DIR/.env.local"
  [[ -f "$env_file" ]] || return 0
  set -a
  # shellcheck disable=SC1090
  source <(grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "$env_file" | sed 's/\r$//')
  set +a
}

stop_preview() {
  if [[ -f "$PID_FILE" ]]; then
    local pid
    pid="$(cat "$PID_FILE")"
    if kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null || true
      echo "Stopped preview server (pid ${pid})."
    fi
    rm -f "$PID_FILE"
  fi
  if command -v lsof >/dev/null 2>&1; then
    local port_pid
    port_pid="$(lsof -ti "tcp:${PORT}" -sTCP:LISTEN 2>/dev/null || true)"
    if [[ -n "$port_pid" ]]; then
      kill $port_pid 2>/dev/null || true
      echo "Freed port ${PORT}."
    fi
  fi
}

wait_for_ready() {
  local url="http://${HOST}:${PORT}/api/matches"
  for _ in $(seq 1 60); do
    if curl -sf -o /dev/null "$url"; then
      return 0
    fi
    sleep 1
  done
  echo "Preview server did not become ready. Log: ${LOG_FILE}" >&2
  return 1
}

NO_BUILD=0
FOREGROUND=0
if [[ "${1:-}" == "--stop" ]]; then
  stop_preview
  exit 0
fi
if [[ "${1:-}" == "--status" ]]; then
  preview_status
  exit $?
fi
if [[ "${1:-}" == "--no-build" ]]; then
  NO_BUILD=1
fi
if [[ "${1:-}" == "--foreground" ]]; then
  FOREGROUND=1
  # Foreground mode is for keeping the server alive — skip rebuild unless requested.
  if [[ "${FOTTY_PREVIEW_REBUILD:-0}" != "1" ]]; then
    NO_BUILD=1
  fi
fi
if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
  exit 0
fi

load_env_local

# Mirror production security posture on localhost.
unset NEXT_PUBLIC_FOTTY_ALLOW_LOCAL_AUTH
export NODE_ENV=production
export PORT="$PORT"
export HOSTNAME="$HOST"
export NEXT_PUBLIC_SITE_URL="http://${HOST}:${PORT}"
export FOTTY_WATCH_STREAM_SECRET="${FOTTY_WATCH_STREAM_SECRET:-local-preview-watch-secret}"

cd "$WEB_DIR"

PREVIEW_BUILD_ENV="$WEB_DIR/.env.production.local"
write_preview_build_env() {
  cat >"$PREVIEW_BUILD_ENV" <<EOF
# Generated by tools/web-preview-local.sh — local production preview only.
NEXT_PUBLIC_SITE_URL=http://${HOST}:${PORT}
NEXT_PUBLIC_FOTTY_ALLOW_LOCAL_AUTH=
FOTTY_WATCH_STREAM_SECRET=${FOTTY_WATCH_STREAM_SECRET}
EOF
}

if [[ "$NO_BUILD" -eq 0 ]]; then
  echo "Building standalone production bundle for http://${HOST}:${PORT} …"
  write_preview_build_env
  npm run build:standalone
  node ./scripts/prepare-standalone.mjs
fi

if [[ ! -f "$WEB_DIR/.next/standalone/server.js" ]]; then
  echo "Missing .next/standalone/server.js — run without --no-build first." >&2
  exit 1
fi

if [[ "$NO_BUILD" -eq 1 ]]; then
  node ./scripts/prepare-standalone.mjs
fi

stop_preview
start_server

if [[ "$FOREGROUND" -eq 1 ]]; then
  exit 0
fi

wait_for_ready

CSS_PATH="$(curl -sf "http://${HOST}:${PORT}/" | grep -oE '/_next/static/[^" ]+\.css' | head -1 || true)"
if [[ -n "$CSS_PATH" ]]; then
  CSS_CODE="$(curl -sf -o /dev/null -w "%{http_code}" "http://${HOST}:${PORT}${CSS_PATH}" || echo 000)"
  if [[ "$CSS_CODE" != "200" ]]; then
    echo "WARNING: stylesheet ${CSS_PATH} returned HTTP ${CSS_CODE}. Try a full rebuild." >&2
  fi
fi

echo ""
echo "Local preview is up (production build, live site unchanged)."
echo "  App:    http://${HOST}:${PORT}"
echo "  Board:  http://${HOST}:${PORT}/swarm"
echo "  Admin:  http://${HOST}:${PORT}/admin"
echo "  Log:    ${LOG_FILE}"
echo "  Stop:   ./tools/web-preview-local.sh --stop"
echo ""
echo "Watch testing: sign in with PocketBase, or use a seeded grant (e.g. test@test.com via /admin)."
echo "Smoke:  FOTTY_WEB_BASE_URL=http://${HOST}:${PORT} npm run smoke"
echo ""
echo "If Safari looks unstyled: Develop → Empty Caches, then hard refresh (Cmd+Shift+R)."
